# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYSDatePickerTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYSDatePickerTest

  target 'LYSDatePickerTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYSDatePickerTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'LYSDatePicker', '~> 0.0.1'
end
